# Generated by Django 2.2.7 on 2020-02-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Article',
        ),
    ]
